executor: slurm
jobs: 100

resources:
  predict_slots: 3

default-resources:
  slurm_partition: "workq"
  slurm_account: "fforge"
  mem: 16GB
  time: 96:00:00
  threads: 1
  cpus_per_task: 1

set-resources:
    predict:
      slurm_partition: "gpuq"
      slurm_extra: "'--gres=gpu:A100_1g.10gb:1'"
