executor: slurm
jobs: 100

default-resources:
  slurm_partition: "workq"
  slurm_account: "fforge"
  mem: 16GB
  time: 96:00:00
  threads: 1
  cpus_per_task: 1

set-resources:
    predict:
      cpus_per_task: 32
      mem: 32GB

    analysis:
      mem: 32GB
