workdir: work
output_repo: experience/Test
genome: ../test_resources/test_genome/sequence.fa
experiments: experiments.tsv
region: chr9:1-32000000
muttype: shuffle
nb_random: 2
distrib: shuffle_bins
resol_model: 32Mb
mpos: 15_872_000
no_cuda: True
gpu_mem: 4
score_types: insulation_count,PC1
merged_by: rdm
resol: None
show_rdm: False
resol_comp: 32Mb
descrip_comp: Comparison between wanted and random mutations for the deviation of the scores
data_file_comp: experience/scores_data_shuf_bins_0_32Mb.csv
analysis_path_comp: experience/result_analysis
output_file_comp: Comparison_scores_32Mb_shuf_bins_0_32Mb.pdf
score_types_comp: insulation_count,PC1
rename: True
create_data_file: True
